[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "fastapi_client_cn"
readme = "README.md"
version = "1.0.0"
requires-python = ">= 3.8"
dependencies = [
    "fastapi[standard]"
]